### PR TITLE
Make ES6 compatible module, use shims in wrapper.

### LINKED ISSUE #1: Would appreciate an ES6-only build
Congrats - I find this to be the best lightweight implementation of a Promise based Xhr.

However I'd like to use it in a project, where I'm having `core-js` for all ES6 browser polyfills, so I find it quite redundant having to pull in `bluebird` and `extend` libraries just for this project.

Is there any chance of having the build process producing two versions of the library: 
one like now 
and one where it is assumed that `Promise` already exists and `extend` is `Object.assign`. 

Sorry, for not being familiar with coffeescript, otherwise I'd write a PR myself.

Thanks

### PR DESCRIPTION
**Pull request by zeekay**
This switch makes it possible to easily include your own
`Promise`/`Object.assign` polyfills (if desired) by directly requiring
`xhr-promise/lib/xhr-promise`. I also dropped `bluebird`/`extend` in favor of
smaller shims in the case xhr-promise is directly required. With shims the
compiled bundle is only 7.7KB minified vs 77KB with `bluebird`/`extend`.

Updated Gruntfile.js + tests to use new bundle. Might also make sense to make
the non-polyfilled version the new default and expose polyfilled bundle
separately.

Fixes #1.

### CODE REVIEW

**Comment by davidtai** [comment]
I would also find this useful. Currently returning a Promise polyfill in place of require('bluebird') which requires a lot of messy bundling hacks.

**Comment by scottbrady** [comment]
Very cool.  I'll take a closer look at the code this evening.  Thanks.

**Comment by scottbrady** [comment]
Merged.  Release forthcoming.  Thanks!

**Comment by zeekay** [comment]
Thanks! I've found it useful to just expose the Promise as well...

```
module.exports = class XMLHttpRequestPromise

  @DEFAULT_CONTENT_TYPE: 'application/x-www-form-urlencoded; charset=UTF-8'
  @Promise: Promise
 ...
```

And use `@Promise` internally. This makes patching in a desired promise implementation easy.

**Pull request closed without merging**
